version: "3"
services:
  halo:
    image: halohub/halo:2.18.0
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - /project/sandbox/data/halo:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s      
    command:
      - --spring.r2dbc.url=r2dbc:pool:postgresql://halodb/halo
      - --spring.r2dbc.username=halo
      # PostgreSQL 的密码，请保证与下方 POSTGRES_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=VAK27UEenN6FDM
      - --spring.sql.init.platform=postgresql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=https://www.cxkun.top
  
  halodb:
    image: postgres:latest
    container_name: halodb
    restart: on-failure:3
    networks:
      halo_network:
    volumes:
      - /project/sandbox/data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=VAK27UEenN6FDM
      - POSTGRES_USER=halo
      - POSTGRES_DB=halo
      - PGUSER=halo

  cloudflared:
     restart: always
     network_mode: host
     environment:
         - TZ=Asia/Shanghai
     command: tunnel --edge-ip-version auto --protocol quic --heartbeat-interval 10s run --token eyJhIjoiYWI0ZjQ5YjVjNjJhZDQ4MmM1MmYzZjA2Nzg3OTQ0M2UiLCJ0IjoiYmJkYmU1Y2MtYWJiMy00ZTcxLWI1ZWYtYWY4Y2FhMzEzYTljIiwicyI6Ik1USTBZV05pWVRBdE9EVTBPQzAwTlRBNExXSmlOV0V0TnpRNFpXRXlZakF5TW1JNCJ9
     container_name: cloudflared
     image: cloudflare/cloudflared:latest    

networks:
  halo_network:
